/*
 *  SCModelActions.h
 *  Sensible TableView
 *  Version: 3.3.0
 *
 *
 *	THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY UNITED STATES 
 *	INTELLECTUAL PROPERTY LAW AND INTERNATIONAL TREATIES. UNAUTHORIZED REPRODUCTION OR 
 *	DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES. YOU SHALL NOT DEVELOP NOR
 *	MAKE AVAILABLE ANY WORK THAT COMPETES WITH A SENSIBLE COCOA PRODUCT DERIVED FROM THIS 
 *	SOURCE CODE. THIS SOURCE CODE MAY NOT BE RESOLD OR REDISTRIBUTED ON A STAND ALONE BASIS.
 *
 *	USAGE OF THIS SOURCE CODE IS BOUND BY THE LICENSE AGREEMENT PROVIDED WITH THE 
 *	DOWNLOADED PRODUCT.
 *
 *  Copyright 2012-2013 Sensible Cocoa. All rights reserved.
 *
 *
 *	This notice may not be removed from this file.
 *
 */


#import <Foundation/Foundation.h>

@class SCTableViewModel;
@class SCArrayOfItemsModel;
@class SCTableViewSection;

typedef void(^SCModelAction_Block)(SCTableViewModel *tableModel);
typedef void(^SCDidAddSectionAction_Block)(SCTableViewModel *tableModel, SCTableViewSection *section, NSUInteger sectionIndex);
typedef void(^SCSortSectionsAction_Block)(SCTableViewModel *tableModel, NSMutableArray *sections);

typedef void(^SCDidFetchModelItemsAction_Block)(SCArrayOfItemsModel *itemsModel, NSMutableArray *items);
typedef NSString*(^SCSectionHeaderTitleForItemAction_Block)(SCArrayOfItemsModel *itemsModel, NSObject *item, NSUInteger itemIndex);


/****************************************************************************************/
/*	class SCModelActions	*/
/****************************************************************************************/ 
/**	
 This class hosts a set of model action blocks. Once an action is set to a desired code block, it will execute the block as soon as the action occurs.
 
 @see SCSectionActions, SCCellActions.
 */

@interface SCModelActions : NSObject



//////////////////////////////////////////////////////////////////////////////////////////
/// @name Actions
//////////////////////////////////////////////////////////////////////////////////////////

/** Action gets called as soon as a section has been added to the model.
 
 This action is typically used to customize automatically generated sections (e.g.: sections generated by SCArrayOfObjectsModel).
 
 Example:
    modelActions.didAddSection = ^(SCTableViewModel *tableModel, SCTableViewSection *section, NSUInteger sectionIndex)
    {
        // use custom data sorting for the first section in a Core Data SCArrayOfObjectsModel
        if(sectionIndex==0 && [section isKindOfClass:[SCArrayOfObjectsSection class]])
        {
            SCArrayOfObjectsSection *objectsSection = (SCArrayOfObjectsSection *)section;
            SCCoreDataFetchOptions *oldFetchOptions = (SCCoreDataFetchOptions *)objectsSection.dataFetchOptions;
            objectsSection.dataFetchOptions = [SCCoreDataFetchOptions optionsWithSortKey:oldFetchOptions.sortKey sortAscending:FALSE filterPredicate:oldFetchOptions.filterPredicate];
        }
    };
 
 */
@property (nonatomic, copy) SCDidAddSectionAction_Block didAddSection;

/** Action gets called to give you a chance to provide custom section sorting.
 
 Example:
    modelActions.sortSections = ^(SCTableViewModel *tableModel, NSMutableArray *sections)
    {
        // Rearrange the 'sections' mutable array here as you see fit
    };
 
 @note To have the model automatically sort its sections alphabetically, simply set its 'autoSortSections' property to TRUE.
 
 */
@property (nonatomic, copy) SCSortSectionsAction_Block sortSections;

/** Action gets called as soon as the model has refreshed its contents after returning from a pull-to-refresh operation.
 
 Example:
    modelActions.didRefresh = ^(SCTableViewModel *tableModel)
    {
        NSLog(@"The model has been refreshed.");
    };
 
 */
@property (nonatomic, copy) SCModelAction_Block didRefresh;

//////////////////////////////////////////////////////////////////////////////////////////
/// @name SCArrayOfItemsModel Actions
//////////////////////////////////////////////////////////////////////////////////////////


/** Action gets called as soon as the model has retrieved its items from their data store.
 
 This action is typically used to customize the 'items' array after it has been fetched from the data store. Items can be added, removed, or rearranged. The added items can either be objects that are suppored by the data store, or normal SCTableViewCell (or subclass) objects.
 
 Example:
    modelActions.didFetchItemsFromStore = ^(SCArrayOfItemsModel *itemsModel, NSMutableArray *items)
    {
        // Add a button cell at the end of the fetched items list
        SCTableViewCell *buttonCell = [SCTableViewCell cellWithText:@"Tap me!" textAlignment:UITextAlignmentCenter];
        buttonCell.cellActions.didSelect = ^(SCTableViewCell *cell, NSIndexPath *indexPath)
        {
            NSLog(@"buttonCell tapped!");
        };
 
        [items addObject:buttonCell];
    };
 
 @note This action is only applicable to SCArrayOfItemsModel subclasses, such as SCArrayOfObjectsModel. 
 
 */
@property (nonatomic, copy) SCDidFetchModelItemsAction_Block didFetchItemsFromStore;


/** Action gets called when SCArrayOfItemsModel requests a section header title for each of its items.
 
 Use this action to control how the automatically generated sections are created. In the following example, a new section will be created for each group of items sharing the same first letter (i.e.: items will be grouped alphabetically).
 
 Example:
    modelActions.sectionHeaderTitleForItem = ^NSString*(SCArrayOfItemsModel *itemsModel, NSObject *item, NSUInteger itemIndex)
    {
        NSString *objectName = (NSString *)[item valueForKey:@"firstName"];
 
        // Return first charcter of objectName
        return [[objectName substringToIndex:1] uppercaseString];
    };
 */
 @property (nonatomic, copy) SCSectionHeaderTitleForItemAction_Block sectionHeaderTitleForItem;



//////////////////////////////////////////////////////////////////////////////////////////
/// @name Miscellaneous
//////////////////////////////////////////////////////////////////////////////////////////

/** The owner table view model of the actions object.
 *
 * @warning This property gets set automatically by the framework, you should never set this property manually */
@property (nonatomic, weak) SCTableViewModel *ownerTableViewModel;

/** Method assigns all the actions of another 'SCModelActions' class to the current one.
 
 @param actions The source 'SCModelActions' class.
 @param override Set to TRUE to override any existing actions, otherwise set to FALSE.
 */
- (void)setActionsTo:(SCModelActions *)actions overrideExisting:(BOOL)override;

@end
